# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveIntegerField(verbose_name='Number of cases')),
                ('residency_region', models.CharField(max_length=255, verbose_name='Region')),
                ('residency_district', models.CharField(max_length=255, verbose_name='District')),
                ('residency_commune', models.CharField(max_length=255, verbose_name='Commune')),
                ('residency_village', models.CharField(max_length=255, verbose_name='Village')),
                ('date_of_hospitalization', models.DateTimeField(verbose_name='Hospitalization date')),
                ('confirm_number', models.PositiveIntegerField(verbose_name='Confirmed')),
                ('probable_number', models.PositiveIntegerField(verbose_name='Probable')),
                ('suspected_number', models.PositiveIntegerField(verbose_name='Suspected')),
                ('severity_level', models.CharField(max_length=255, verbose_name='Severity Level')),
            ],
            options={
                'db_table': 'animal_case',
                'verbose_name': 'Animal Case',
                'verbose_name_plural': 'Animal Cases',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('incubation_period', models.PositiveIntegerField(verbose_name='Incubation period')),
                ('symptoms', models.CharField(max_length=255, verbose_name='Symptoms')),
            ],
            options={
                'db_table': 'disease',
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Disease',
            },
        ),
        migrations.CreateModel(
            name='HumanCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveIntegerField(verbose_name='Number of cases')),
                ('residency_region', models.CharField(max_length=255, verbose_name='Region')),
                ('residency_district', models.CharField(max_length=255, verbose_name='District')),
                ('residency_commune', models.CharField(max_length=255, verbose_name='Commune')),
                ('residency_village', models.CharField(max_length=255, verbose_name='Village')),
                ('date_of_hospitalization', models.DateTimeField(verbose_name='Hospitalization date')),
                ('confirm_number', models.PositiveIntegerField(verbose_name='Confirmed')),
                ('probable_number', models.PositiveIntegerField(verbose_name='Probable')),
                ('suspected_number', models.PositiveIntegerField(verbose_name='Suspected')),
                ('severity_level', models.CharField(max_length=255, verbose_name='Severity Level')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_reporter.Disease')),
            ],
            options={
                'db_table': 'human_case',
                'verbose_name': 'Human Case',
                'verbose_name_plural': 'Human Cases',
            },
        ),
        migrations.AddField(
            model_name='animalcase',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_reporter.Disease'),
        ),
    ]
