# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporter', '0002_auto_20160420_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalcase',
            old_name='confirm_number',
            new_name='confirm_count',
        ),
        migrations.RenameField(
            model_name='animalcase',
            old_name='probable_number',
            new_name='probable_count',
        ),
        migrations.RenameField(
            model_name='animalcase',
            old_name='suspected_number',
            new_name='suspected_count',
        ),
        migrations.RenameField(
            model_name='humancase',
            old_name='confirm_number',
            new_name='confirm_count',
        ),
        migrations.RenameField(
            model_name='humancase',
            old_name='probable_number',
            new_name='probable_count',
        ),
        migrations.RenameField(
            model_name='humancase',
            old_name='suspected_number',
            new_name='suspected_count',
        ),
    ]
