# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporter', '0003_auto_20160420_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalcase',
            name='date_of_hospitalization',
        ),
        migrations.RemoveField(
            model_name='humancase',
            name='date_of_hospitalization',
        ),
        migrations.AddField(
            model_name='animalcase',
            name='end_period',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 12, 50, 51, 817593, tzinfo=utc), verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalcase',
            name='start_period',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 12, 50, 57, 99719, tzinfo=utc), verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humancase',
            name='end_period',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 12, 51, 4, 918603, tzinfo=utc), verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humancase',
            name='start_period',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 12, 51, 12, 926032, tzinfo=utc), verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
