# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporter', '0004_auto_20160420_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalcase',
            old_name='case_number',
            new_name='case_count',
        ),
    ]
