# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporter', '0005_auto_20160420_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalcase',
            old_name='residency_district',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='residency_region',
        ),
        migrations.AddField(
            model_name='animalcase',
            name='village',
            field=models.CharField(default='', max_length=255, verbose_name='District'),
            preserve_default=False,
        ),
    ]
