# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporter', '0006_auto_20160420_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalcase',
            name='confirm_count',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='end_period',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='probable_count',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='residency_commune',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='residency_village',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='severity_level',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='start_period',
        ),
        migrations.RemoveField(
            model_name='animalcase',
            name='suspected_count',
        ),
        migrations.AddField(
            model_name='animalcase',
            name='fatality_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Fatality rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalcase',
            name='morbidity_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Morbidity rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalcase',
            name='mortality_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Mortality rate'),
            preserve_default=False,
        ),
    ]
