# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporter', '0008_auto_20160420_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humancase',
            old_name='residency_district',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='humancase',
            name='residency_region',
        ),
        migrations.AddField(
            model_name='humancase',
            name='hospitalization_avg',
            field=models.PositiveIntegerField(default=1, verbose_name='Hospitalization average time '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humancase',
            name='laboratory_avg',
            field=models.PositiveIntegerField(default=1, verbose_name='Laboratory average time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humancase',
            name='report_avg',
            field=models.PositiveIntegerField(default=1, verbose_name='Report average time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humancase',
            name='sampling_avg',
            field=models.PositiveIntegerField(default=1, verbose_name='Sampling average time'),
            preserve_default=False,
        ),
    ]
